### ISSUE TITLE
httpVersion should be a string

### ISSUE THREAD

**Issue by hsch** [jamiemccrindle/lambda-router-adapter#1]
Currently, the request's httpVersion is coded as a floating-point number: https://github.com/jamiemccrindle/lambda-router-adapter/blob/master/request.js#L22

I think this should be a string.

- Floating-point numbers are known to have precision issues, and even if it works in the 1.1 case, it looks like a bad pattern to me. Surprising side effects might occur when printing (formatting it as a string) or parsing the version into major/minor components.
- It's a string in the Node.js source: https://github.com/nodejs/node/blob/db1087c9757c31a82c50a1eba368d8cba95b57d0/lib/_http_common.js#L63
- It's a string in Express:

  Code:
  
      var express = require('express');
      var app = express();
      app.get('/', function (req, res) {
        res.send('typeof req.httpVersion = ' + typeof req.httpVersion);
      });
      app.listen(3000);
  
  Response:

      typeof req.httpVersion = string

**Comment by jamiemccrindle** [comment]
This was fixed by https://github.com/jamiemccrindle/lambda-router-adapter/pull/2

Thanks @hsch!

**Comment by hsch** [comment]
I think you closed my pull request #2 and didn't merge it. The request.js on master still has the 1.1 float.  I think I might have messed up the references (issues to pull requests and vice versa) at one point, so maybe you can check again?

**Comment by jamiemccrindle** [comment]
Have made the change. Thanks again.
