### ISSUE TITLE
Legacy context functions still in use

### ISSUE THREAD

**Issue by hsch** [jamiemccrindle/lambda-router-adapter#7]
With the latest Node.js runtime, AWS Lambda advises the use of a new, third callback parameter instead of context functions: http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-using-old-runtime.html#transition-to-new-nodejs-runtime

lambda-router-adapter should use the new callback when available.

**Comment by jamiemccrindle** [comment]
Sure thing! Will check. Thanks again for the contribution

**Comment by hsch** [comment]
I think your previous comment was meant for #1, but the mail/Github integration failed. Regarding this issue (#7), I'm preparing another pull request (which I cannot test currently due to very limited bandwidth).

**Comment by hsch** [comment]
There it is.
