### ISSUE TITLE
Publish new version to npm

### ISSUE THREAD

**Issue by hsch** [jamiemccrindle/lambda-router-adapter#9]
After several issues have been fixed (namely #1, #3, #5, and #7) which seem critical for compatibility with today's AWS Lambda environment, it would be great to have these changes in the official npm artifact as well: https://www.npmjs.com/package/lambda-router-adapter

Please publish a new version that includes the fixes. :)

Thank you!
Hendrik

**Comment by jamiemccrindle** [comment]
done!

**Comment by hsch** [comment]
Awesome, thank you for all the quick merges and responses!
